#!/bin/sh

DAY=${1:-$(date +%d)}
YEAR=${2:-$(date +%Y)}
README="$YEAR/README.md"
URL="https://adventofcode.com/$YEAR/day/$DAY"
SESSION_ID="53616c7465645f5f04b2136e6699d570893ac2fc01269e64ac4449b426eb48723db7cdd29195f6663315832b4906e8c8"

git checkout -b "$YEAR/day-$DAY"

echo "" >> $README
echo "### Day $DAY" >> $README
echo "* Puzzle: []($URL)" >> $README
echo "* Solution: [``](day-$DAY/)" >> $README
echo "* Language: " >> $README

mkdir "$YEAR/day-$DAY"
cd "$YEAR/day-$DAY"
touch input
curl "$URL/input" -H "Cookie: session=$SESSION_ID" > input
